<Project>
    <Import Project="$(MSBuildThisFileDirectory)Directory.Build.Ocelot.Graph.props"/>

    <ItemGroup>
        <ProjectReference Include="$(MSBuildThisFileDirectory)Ocelot/Ocelot.Chain/Ocelot.Chain.csproj"/>
        <ProjectReference Include="$(MSBuildThisFileDirectory)Ocelot/Ocelot.Pictomancy/Ocelot.Pictomancy.csproj"/>
        <ProjectReference Include="$(MSBuildThisFileDirectory)Ocelot/Ocelot.Rotation/Ocelot.Rotation.csproj"/>
    </ItemGroup>
</Project>
